language: ruby
cache: bundler
rvm:
  - 2.5.3
notifications:
  slack:
    secure: JR3tcXf1UljXxf3i1FgVeM4gA/KHgqPmPziknIHqahB+50LrD7ExaYqFcHm6dvZomO/iwrBNSYpMxtHUcAT33+R93EM8kKMqoaCKUSPd3ueW5jNn8zods87u+HxS3UAb0hYwHmN8GWvasCFBnSBELCRmuRXd6qn8r3nuqyPJkuo=
env:
  global:
    - CC_TEST_REPORTER_ID=957fa7b7d88d5482dede502364d2fff8763ea30ee7d1de53000c14288a76ed4c
    - RAILS_ENV=test
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake db:schema:load
  - make test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
