# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db71ae76f5fad4a4fa281abc341f17465e4a5f49c5922fb7fa624fa7872ba89c36a7316dface2a2121b07408477432cfc4615037fbf0fdb407ab3c097400d3f

test:
  secret_key_base: d61f109d97fdf3b2a1e922f2800d3048e2fe7e956b6b386b66866b086ff17b9972004dfb7997c270d228f235359880348e1de931c3b0f96606957c40be1a0dc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
